### ISSUE TITLE
Need a Help, in getting FileOutputStream or File

### ISSUE THREAD

**Issue by Meet-Miyani** [drahovac/android-file-save#15]
I checked your project, which was a bit complicated for me to understand as I am an intermediate.
I wanted the FileOutputStream or File can also work, but I am unable to understand or find, how to read the result in viewmodel, as it returns the SaveSuccess String, after the succesfull file creation.

**Your interface**
```
sealed interface FileSaveResult {

    data class SaveSuccess(val successData: Uri) : FileSaveResult

    object MissingWritePermission : FileSaveResult

    data class SaveError(val exception: Throwable?) : FileSaveResult
}
```

**My Implemented Interface**
```
interface StreamResult {

    data class StreamSuccess(val stream: FileOutputStream?) : StreamResult

    object MissingWritePermission : StreamResult

    data class StreamError(val exception: Throwable?) : StreamResult

}
```
**And in the Main Activity, I am getting the Successful Stream Log**
```
val mainViewModel = ViewModelProvider(this)[MainViewModel::class.java]
        mainViewModel.pdfSaveResult.observe(this){
            Log.d(TAG, "onCreate: $it")
        }
```

These are the Logs:
**This one is before the Button Clicked**
`Main_Activity: onCreate: com.example.filesavingproejct_git.MainViewModel$pdfSaveResult$1@92b5a78
`
**And this one is after clicking the Button, to get the Stream**
`Main_Activity: onCreate: StreamSuccess(stream=java.io.FileOutputStream@21755ab)`

**Comment by vdrahorad** [comment]
Hello, I am not sure what the you mean by -  how to read the result in viewmodel.

The problem this project tries to solve, is how to save file in public folders Downloads and Images, 
so that you can export pe. image obtained from your app to gallery etc. This is reason why FileSaveResult returns Uri 
of saved file, so we can inform user that his file was sucessfully saved (and using uri you can navigate him to gallery to open image etc). 
So in sample app if you click on Save Image button, sample image is saved in images folder and you should be able to find it in gallery.

I am not sure what you are trying to achieve or what would you like to have in log.

**Comment by Meet-Miyani** [comment]
Yes, I understood your purpose for the Project.
But I am trying to achieve the FileOutputStream, after adding the File into the Storage, in your code, the **SaveSuccess** data class is inside the interface, so I tried to replicate the same for the StreamResult interface, and it worked too. it open the **FileOutputStream** for a **new file**. But the problem is, **ViewModel** functions convert the **StreamResult** into String,

I tried using the type **<StreamResult>**, and also got the observation in the main activity, which is this log
`Main_Activity: onCreate: StreamSuccess(stream=java.io.FileOutputStream@21755ab)`
Says, the stream is successful, but the thing is, the **output-stream** object is converted into String, which I can't use.

As the **StreamResult** is an **interface**, I can't access the **StreamSuccess** data class or, the Stream
I have never implemented any code with this much proficiency, that's why It's getting complicated for me to understand.
I took a hard time reading your project. Your code skills are too good.

**Comment by vdrahorad** [comment]
Well, first thing - result converted to string - you are using Log method -   Log.d(TAG, "onCreate: $it"), so in log, toString method is  called on  result object (log prints string so it must be converted to string) and you got default output of toString method of data class https://kotlinlang.org/docs/data-classes.html
To access stream field of StreamSuccess - you first have to cast it - I suggest reading kotlin docs - https://kotlinlang.org/docs/typecasts.html
So you can do something like 
 mainViewModel.pdfSaveResult.observe(this){
           (it as? StreamSuccess).stream.doWhaterveYouNeedWithStream
        }
Or even better using when and smart cast

when (it) {
    is StreamSuccess-> it.stream....
    is MissingWritePermission -> requestPermission()
    is StreamError-> handleError(handleException(it.exception))
}

**Comment by Meet-Miyani** [comment]
Thanks a lot, Man
I didn't know, I have to typecast it.
It worked.!

I did it like this
```

val mainViewModel = ViewModelProvider(this)[MainViewModel::class.java]
        mainViewModel.pdfSaveResult.observe(this){
           when(it){
               is StreamResult.StreamSuccess->{
                   Log.d(TAG, "onCreate: ${it.stream}")
               }
           }
        }

```

And received the Stream, I was using log to check whether I receiving the Stream, or not.
I want to use it, to save PDF using iText library.
I received it.
`D/Main_Activity: onCreate: java.io.FileOutputStream@fa574d8`

Thanks Again.!
I would like to connect to you, on Linked-In, if you present on it.
